export {
  uid,
  createNote,
  createRest,
  createMeasure,
  createPart,
  createScore,
  addMeasure,
  addNote,
  removeNote,
  PIANO,
  GUITAR_STANDARD,
  ELECTRIC_GUITAR,
  BASS_GUITAR,
  DRUM_SET,
  UKULELE,
  BANJO,
  MANDOLIN,
  FLUTE,
  CLARINET,
  SAXOPHONE_ALTO,
  SAXOPHONE_TENOR,
  TRUMPET,
  TROMBONE,
  VIOLIN,
  VIOLA,
  CELLO,
  DOUBLE_BASS,
  VOICE_SOPRANO,
  VOICE_ALTO,
  VOICE_TENOR,
  VOICE_BASS,
  HARPSICHORD,
  ORGAN,
  ACCORDION,
  PRESET_INSTRUMENTS,
  TEMPLATES,
  type TemplateKey,
} from './factories.ts';

export { CommandHistory } from './commands.ts';
export type { Command } from './commands.ts';

export {
  InsertNoteCommand,
  InsertRestCommand,
  DeleteNoteCommand,
  ReplaceNoteCommand,
  ModifyNoteCommand,
  InsertMeasureCommand,
  DeleteMeasureCommand,
  ChangeAttributesCommand,
} from './editCommands.ts';

export {
  getDurationInQuarters,
  getMeasureDuration,
  getEffectiveTimeSignature,
  getMeasureCapacity,
  canAddToMeasure,
  isMeasureFull,
  getRemainingSpace,
  findNextAvailableMeasure,
} from './duration.ts';
